alatka:
  connection:
    classpath: ""
    default:
      logger:
        info: "'payload: ' + payload + '; headers: ' + headers"
        error: "payload"
      taskExecutor:
        corePoolSize: 2
        maxPoolSize: 5
        queueCapacity: 5
        keepAliveSeconds: 60
        threadNamePrefix: alatka-connection-
      taskScheduler:
        corePoolSize: 2
        threadNamePrefix: alatka-connection-scheduler-
      pollerMetadata:
        period: 200
        maxPerPoll: 1000